# Generated by Django 2.0 on 2017-12-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('current_hash', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
