# Generated by Django 2.0 on 2017-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171220_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proof_of_work',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
