# Generated by Django 2.0 on 2017-12-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171220_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proof_of_work',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
